name: Wangana
description:  Jekyll theme

sass:
  sass_dir: assets/css/_sass
  style: :compressed

url: https://iamnii.github.io/wangana
permalink: /:year/:month/:title/
owner:
    name: #
    twitter: #
    github: #
    disqus_shortname: #

ga_id: #
ga_username: #

timezone: Africa/Accra
